### ISSUE TITLE
Compile libedk.so.3.3.3 in linux 86x_64

### ISSUE THREAD

**Issue by cabelo** [Emotiv/community-sdk#186]
When I compile with the library version 3.3.2. Everything is OK
cd EmoStateLogger
$ g++ main.cpp -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I~/community-sdk/include -L~/community-sdk/bin/linux64/ -ldbus-1  -ledk 

When I compile with the library version 3.3.3. Show this error below:

cd EmoStateLogger
$ g++ main.cpp -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I~/community-sdk/include -L~/community-sdk/bin/linux64/ -ldbus-1  -ledk 
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_set_error_from_message@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_copy@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_watch_get_enabled@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_close@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_watch_set_data@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_get_args@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_get_object_path_data@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_set_timeout_functions@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_iter_append_basic@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_bus_get_private@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_send@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_type_is_container@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_get_dispatch_status@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_timeout_get_interval@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_iter_open_container@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_watch_get_unix_fd@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_iter_get_signature@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_error_free@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_pending_call_unref@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_timeout_set_data@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_pending_call_steal_reply@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_ref@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_bus_remove_match@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_set_watch_functions@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_get_sender@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_set_error@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_append_args@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_iter_recurse@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_iter_get_fixed_array@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_type_is_basic@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_watch_get_flags@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_unref@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_get_signature@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_watch_handle@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_pending_call_cancel@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_get_no_reply@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_iter_init@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_get_is_connected@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_add_filter@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_get_path@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_pending_call_set_notify@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_is_method_call@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_iter_get_basic@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_timeout_handle@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_error_is_set@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_timeout_get_enabled@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_dispatch@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_has_signature@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_register_object_path@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_unregister_object_path@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_iter_close_container@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_iter_get_arg_type@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_append_args_valist@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_get_interface@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_bus_get@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_bus_add_match@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_new@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_new_method_call@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_send_with_reply@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_type_is_fixed@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_get_member@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_free@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_unref@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_error_init@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_bus_request_name@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_bus_get_unique_name@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_ref@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_set_no_reply@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_malloc0@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_new_method_return@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_new_signal@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_new_error@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_iter_init_append@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_remove_filter@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_get_type@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_free_string_array@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_set_exit_on_disconnect@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_iter_append_fixed_array@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_list_registered@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_connection_set_dispatch_status_function@LIBDBUS_1_3'
/dados/Fontes/opensource/community-sdk/bin/linux64//libedk.so: undefined reference to `dbus_message_iter_next@LIBDBUS_1_3'
collect2: error: ld returned 1 exit status

**Comment by havietnam** [comment]
You need to upgrade dbus to 1.3
`sudo apt-get install libdbus-1-3 libdbus-1-dev `
`g++ main.cpp -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I../../../include -L../../../bin/linux64/ -ldbus-1 -ledk`
