### ISSUE TITLE
build error MentalCommandWithLocalProfile for Ubuntu

### ISSUE THREAD

**Issue by koolakoff** [Emotiv/community-sdk#170]
The MentalCommandWithLocalProfile fails to build on Ubuntu (Ubuntu 16.04 LTS)
(I’ve used the How to build C++ examples with Cmake.txt and has turned off all unsupported examples according https://github.com/Emotiv/community-sdk#api-code-example )

```
[ 75%] Linking CXX executable ../../../Programs/MentalCommandWithLocalProfile
CMakeFiles/MentalCommandWithLocalProfile.dir/MentalCommandWithLocalProfile.cpp.o: In function `loadProfile(int)':
MentalCommandWithLocalProfile.cpp:(.text+0x53a): undefined reference to `IEE_LoadUserProfile'
CMakeFiles/MentalCommandWithLocalProfile.dir/MentalCommandWithLocalProfile.cpp.o: In function `trainMentalCommandActions(int)':
MentalCommandWithLocalProfile.cpp:(.text+0x9d3): undefined reference to `IEE_SaveUserProfile'
collect2: error: ld returned 1 exit status
ex
```

Also I had to modify MentalCommandWithLocalProfile.cpp and it's CMakeList (added the `-std=c++1y` and few Linux includes). So looks like MentalCommandWithLocalProfile is not supported for Linux at the moment.

Please advice if this example will be supported for ubuntu? If it is, then where can I find the correct libedk.so

**Comment by koolakoff** [comment]
[log.txt](https://github.com/Emotiv/community-sdk/files/770448/log.txt)
attached the logs

**Comment by koolakoff** [comment]
The similar error with `SavingLoadingCloudProfile`

```
[100%] Linking CXX executable ../../../Programs/SavingLoadingCloudProfile
CMakeFiles/SavingLoadingCloudProfile.dir/main.cpp.o: In function `main':
main.cpp:(.text+0x7cf): undefined reference to `EC_UploadProfileFile'
main.cpp:(.text+0x8ca): undefined reference to `EC_DownloadProfileFile'
collect2: error: ld returned 1 exit status
```

Looks like there is no support for any kind of profile for ubuntu.

**Comment by hoangphamemotiv** [comment]
Hi @koolakoff 

at the moment, we not support Local Profile on Ubuntu yet. (i will reupdate the docs).  but with Cloud Profile, it should works. QA team will check it again. 

Thanks
